/**
 * API request and response type definitions
 * @module types/api
 */

import type {
  Checkbook,
  Allocation,
  WithdrawRequest,
  WithdrawRequestDetail,
  TokenPrice,
  Pool,
  Token,
  UniversalAddress,
  PaginatedResponse,
  UserStats,
  TokenStats,
  MetricsMap,
} from './models';

// ============ Common API Types ============

/**
 * Standard API response wrapper
 */
export interface APIResponse<T = any> {
  /** Success status */
  success: boolean;
  /** Response data */
  data?: T;
  /** Error message if failed */
  error?: string;
  /** Error code if failed */
  errorCode?: string;
  /** Response timestamp */
  timestamp?: number;
}

/**
 * Standard error response
 */
export interface APIError {
  /** Error message */
  message: string;
  /** Error code */
  code: string;
  /** HTTP status code */
  statusCode: number;
  /** Additional error details */
  details?: Record<string, any>;
}

// ============ Authentication ============

/**
 * Authentication request
 */
export interface AuthRequest {
  /** User's universal address */
  address: UniversalAddress;
  /** Chain ID */
  chainId: number;
  /** Signed message */
  signature: string;
  /** Message that was signed */
  message: string;
}

/**
 * Authentication response
 */
export interface AuthResponse {
  /** JWT token */
  token: string;
  /** User's address */
  user_address: UniversalAddress;
}

/**
 * Token refresh request
 */
export interface RefreshTokenRequest {
  /** Current token */
  token: string;
}

/**
 * Token refresh response
 */
export interface RefreshTokenResponse {
  /** New JWT token */
  token: string;
  /** New expiration time */
  expiresAt: number;
}

// ============ Checkbooks (merged with Deposits) ============

/**
 * List checkbooks request
 */
export interface ListCheckbooksRequest {
  /** Owner address (optional, defaults to authenticated user) */
  owner?: string;
  /** Filter by status */
  status?: string;
  /** Filter by token ID */
  tokenId?: string;
  /** Page number */
  page?: number;
  /** Items per page */
  limit?: number;
}

/**
 * List checkbooks response
 */
export interface ListCheckbooksResponse extends PaginatedResponse<Checkbook> {}

/**
 * Get checkbook by ID request
 */
export interface GetCheckbookRequest {
  /** Checkbook ID */
  id: string;
}

/**
 * Get checkbook response
 */
export interface GetCheckbookResponse {
  /** Checkbook data */
  checkbook: Checkbook;
}

// ============ Allocations ============

/**
 * List allocations request
 */
export interface ListAllocationsRequest {
  /** Owner address (optional) */
  owner?: string;
  /** Filter by checkbook ID */
  checkbookId?: string;
  /** Filter by token ID */
  tokenId?: string;
  /** Filter by status */
  status?: string;
  /** Page number */
  page?: number;
  /** Items per page */
  limit?: number;
}

/**
 * List allocations response
 */
export interface ListAllocationsResponse extends PaginatedResponse<Allocation> {}

/**
 * Create allocations (commitment) request
 */
export interface CreateAllocationsRequest {
  /** Checkbook ID */
  checkbookId: string;
  /** Array of amounts */
  amounts: string[];
  /** Token ID */
  tokenId: string;
  /** User's signature */
  signature: string;
  /** Message that was signed */
  message: string;
  /** Commitment hashes (optional, generated by backend if not provided) */
  commitments?: string[];
}

/**
 * Create allocations response
 */
export interface CreateAllocationsResponse {
  /** Created allocations */
  allocations: Allocation[];
  /** Updated checkbook */
  checkbook: Checkbook;
}

// ============ Withdrawals ============

/**
 * List withdrawal requests request
 */
export interface ListWithdrawRequestsRequest {
  /** Owner address (optional) */
  owner?: string;
  /** Filter by status */
  status?: string;
  /** Filter by token ID */
  tokenId?: string;
  /** Filter by target chain */
  targetChain?: number;
  /** Page number */
  page?: number;
  /** Items per page */
  limit?: number;
}

/**
 * List withdrawal requests response
 */
export interface ListWithdrawRequestsResponse extends PaginatedResponse<WithdrawRequest> {}

/**
 * Get withdrawal request by ID request
 */
export interface GetWithdrawRequestRequest {
  /** Withdraw request ID */
  id: string;
}

/**
 * Get withdrawal request response
 */
export interface GetWithdrawRequestResponse {
  /** Withdraw request data with full allocations */
  withdrawRequest: WithdrawRequestDetail;
}

/**
 * Get withdrawal request by nullifier request
 */
export interface GetWithdrawRequestByNullifierRequest {
  /** Nullifier hash */
  nullifier: string;
}

/**
 * Create withdrawal request request
 */
export interface CreateWithdrawRequestRequest {
  /** Checkbook ID */
  checkbookId: string;
  /** Array of allocation IDs */
  allocationIds: string[];
  /** Intent object (matches backend v2 format) */
  intent: {
    type: number; // 0=RawToken, 1=AssetToken
    beneficiaryChainId: number;
    beneficiaryAddress: string;
    tokenIdentifier?: string; // For RawToken
    assetId?: string; // For AssetToken
    preferredChain?: number;
  };
  /** User's signature */
  signature?: string;
  /** Message that was signed */
  message?: string;
  /** Nullifier hash */
  nullifier?: string;
  /** ZK proof (optional, may be generated by backend) */
  proof?: string;
  /** Additional metadata */
  metadata?: Record<string, any>;
}

/**
 * Create withdrawal request response
 */
export interface CreateWithdrawRequestResponse {
  /** Success status */
  success?: boolean;
  /** Created withdraw request data */
  data?: {
    /** Withdraw request ID */
    id: string;
    /** Status */
    status: string;
    /** Proof status */
    proof_status?: string;
    /** Execute status */
    execute_status?: string;
    /** Payout status */
    payout_status?: string;
  };
  /** Created withdraw request (legacy format) */
  withdrawRequest?: WithdrawRequestDetail;
}

/**
 * Retry withdrawal request request
 */
export interface RetryWithdrawRequestRequest {
  /** Withdraw request ID */
  id: string;
}

/**
 * Retry withdrawal request response
 */
export interface RetryWithdrawRequestResponse {
  /** Updated withdraw request */
  withdrawRequest: WithdrawRequest;
}

/**
 * Cancel withdrawal request request
 */
export interface CancelWithdrawRequestRequest {
  /** Withdraw request ID */
  id: string;
}

/**
 * Cancel withdrawal request response
 */
export interface CancelWithdrawRequestResponse {
  /** Success status */
  success?: boolean;
  /** Cancelled withdraw request data */
  data?: WithdrawRequest;
  /** Cancelled withdraw request (legacy format) */
  withdrawRequest?: WithdrawRequest;
}

/**
 * Get withdrawal statistics request
 */
export interface GetWithdrawStatsRequest {
  /** Owner address (optional) */
  owner?: string;
  /** Token ID (optional) */
  tokenId?: string;
}

/**
 * Get withdrawal statistics response
 */
export interface GetWithdrawStatsResponse {
  /** Total withdrawals count */
  totalCount: number;
  /** Pending withdrawals count */
  pendingCount: number;
  /** Completed withdrawals count */
  completedCount: number;
  /** Failed withdrawals count */
  failedCount: number;
  /** Total withdrawn amount */
  totalAmount: string;
  /** Breakdown by token */
  byToken: TokenStats[];
}

// ============ Pools & Tokens ============

/**
 * List pools request
 */
export interface ListPoolsRequest {
  /** Filter by active status */
  isActive?: boolean;
}

/**
 * List pools response
 */
export interface ListPoolsResponse {
  /** Array of pools */
  pools: Pool[];
}

/**
 * Get pool by ID request
 */
export interface GetPoolRequest {
  /** Pool ID */
  id: string;
}

/**
 * Get pool response
 */
export interface GetPoolResponse {
  /** Pool data */
  pool: Pool;
}

/**
 * List tokens request
 */
export interface ListTokensRequest {
  /** Filter by active status */
  isActive?: boolean;
  /** Filter by chain ID */
  chainId?: number;
}

/**
 * List tokens response
 */
export interface ListTokensResponse {
  /** Array of tokens */
  tokens: Token[];
}

/**
 * Get token by ID request
 */
export interface GetTokenRequest {
  /** Token ID */
  id: string;
}

/**
 * Get token response
 */
export interface GetTokenResponse {
  /** Token data */
  token: Token;
}

// ============ Token Prices ============

/**
 * Get token prices request
 */
export interface GetTokenPricesRequest {
  /** Array of token symbols */
  symbols?: string[];
}

/**
 * Get token prices response
 */
export interface GetTokenPricesResponse {
  /** Array of token prices */
  prices: TokenPrice[];
  /** Response timestamp */
  timestamp: number;
}

// ============ User Statistics ============

/**
 * Get user statistics request
 */
export interface GetUserStatsRequest {
  /** User address (optional, defaults to authenticated user) */
  address?: string;
}

/**
 * Get user statistics response
 */
export interface GetUserStatsResponse {
  /** User statistics */
  stats: UserStats;
}

// ============ KMS (Key Management Service) ============

/**
 * KMS signature request
 */
export interface KMSSignRequest {
  /** Data to sign (hex string) */
  data: string;
  /** Key ID to use for signing */
  keyId?: string;
}

/**
 * KMS signature response
 */
export interface KMSSignResponse {
  /** Signature (hex string) */
  signature: string;
  /** Public key used for signing */
  publicKey: string;
}

/**
 * KMS public key request
 */
export interface KMSPublicKeyRequest {
  /** Key ID */
  keyId?: string;
}

/**
 * KMS public key response
 */
export interface KMSPublicKeyResponse {
  /** Public key (hex string) */
  publicKey: string;
  /** Key ID */
  keyId: string;
}

// ============ Health Check ============

/**
 * Health check response
 */
export interface HealthCheckResponse {
  /** Service status */
  status: 'ok' | 'degraded' | 'down';
  /** Current timestamp */
  timestamp: number;
  /** Service version */
  version?: string;
  /** Additional health info */
  details?: Record<string, any>;
}

// ============ Metrics API ============

/**
 * Pool metrics response
 */
export interface PoolMetricsResponse {
  /** Pool ID */
  pool_id: number;
  /** Metrics map (metric_type -> metric) */
  metrics: MetricsMap;
}

/**
 * Token metrics response
 */
export interface TokenMetricsResponse {
  /** Asset Token ID */
  asset_id: string;
  /** Metrics map (metric_type -> metric) */
  metrics: MetricsMap;
}

/**
 * Metrics history data point
 */
export interface MetricsDataPoint {
  /** Timestamp (ISO 8601) */
  timestamp: string;
  /** Metric value */
  value: string;
}

/**
 * Metrics history response
 */
export interface MetricsHistoryResponse {
  /** Pool ID (if pool metrics) */
  pool_id?: number;
  /** Asset ID (if token metrics) */
  asset_id?: string;
  /** Metric type */
  metric_type: string;
  /** Metric display name */
  metric_name: string;
  /** Unit */
  unit: string;
  /** Time-series data points */
  data: MetricsDataPoint[];
}

/**
 * Batch pool metrics response
 */
export interface BatchPoolMetricsResponse {
  /** Map of pool ID to metrics */
  metrics: Record<number, MetricsMap>;
}

/**
 * Batch token metrics response
 */
export interface BatchTokenMetricsResponse {
  /** Map of asset ID to metrics */
  metrics: Record<string, MetricsMap>;
}

// ============ Quote & Preview API ============

/**
 * Route and fees query request
 */
export interface RouteAndFeesRequest {
  /** Owner data (source chain and address) */
  ownerData: UniversalAddress;
  /** Deposit token address */
  depositToken: string;
  /** Withdrawal intent */
  intent: {
    type: 'RawToken' | 'AssetToken';
    beneficiary: UniversalAddress;
    tokenContract?: string;  // For RawToken
    assetId?: string;        // For AssetToken
  };
  /** Amount to withdraw */
  amount: string;
  /** Include Hook execution cost */
  includeHook: boolean;
}

/**
 * Route step information
 */
export interface RouteStep {
  step: number;
  chain: string;
  action: string;
  estimatedTime: string;
}

/**
 * Gas fee information
 */
export interface GasFee {
  chain: string;
  estimatedGas: string;
  currentGasPrice: string;
  gasCostInNative: string;
  gasCostInUSD: string;
  recommendation?: string;
}

/**
 * Bridge fee information
 */
export interface BridgeFee {
  bridgeName: string;
  feeType: string;
  feeInSourceToken: string;
  feeInUSD: string;
  slippage: string;
  minReceived: string;
}

/**
 * Fee summary
 */
export interface FeeSummary {
  totalGasCostUSD: string;
  totalBridgeFeeUSD: string;
  totalCostUSD: string;
  estimatedReceived: string;
}

/**
 * Route and fees response
 */
export interface RouteQuoteResponse {
  route: {
    bridge: string;
    bridgeProtocol: string;
    estimatedTime: string;
    steps: RouteStep[];
  };
  fees: {
    proofGeneration: GasFee;
    executeWithdraw: GasFee;
    bridge: BridgeFee;
    hookExecution?: GasFee;
    summary: FeeSummary;
  };
  timeline: {
    total: string;
    breakdown: Array<{
      stage: string;
      time: string;
    }>;
  };
  warnings: string[];
  meta: {
    quoteId: string;
    validUntil: string;
    timestamp: string;
  };
}

/**
 * Hook asset query request
 */
export interface HookAssetRequest {
  chain: number;
  protocol: 'aave' | 'compound' | 'yearn' | 'lido';
  baseToken: string;
  amount: string;
}

/**
 * Hook asset response
 */
export interface HookAssetResponse {
  asset: {
    protocol: string;
    baseToken: string;
    yieldToken: string;
    tokenAddress: string;
    yield: {
      currentAPY: string;
      apy7d: string;
      apy30d: string;
      source: string;
      lastUpdated: string;
    };
    price: {
      baseTokenPrice: string;
      yieldTokenPrice: string;
      exchangeRate: string;
      priceImpact: string;
    };
    fees: {
      depositFee: string;
      withdrawalFee: string;
      performanceFee: string;
      estimatedFees: {
        inputAmount: string;
        fees: string;
        netReceived: string;
      };
    };
    conversion: {
      input: {
        token: string;
        amount: string;
      };
      output: {
        token: string;
        expectedAmount: string;
        minAmount: string;
        valueInUSD: string;
      };
    };
    protocolHealth: {
      status: 'healthy' | 'warning' | 'critical';
      tvl: string;
      utilizationRate: string;
      available: string;
    };
    risks: Array<{
      type: string;
      level: string;
      description: string;
    }>;
  };
  alternatives?: Array<{
    protocol: string;
    yieldToken: string;
    currentAPY: string;
    reason: string;
  }>;
  meta: {
    dataSource: string;
    lastUpdated: string;
    cacheValidUntil: string;
  };
}

